quizes/urls.py
from django.urls import path
from .views import (QuizListView,quiz_view, quiz_data_view,save_quiz_view,register_page,login_page,logout_user,final_results_page)

app_name = 'quizes'

urlpatterns = [
    
    path('register/',register_page,name='register'),
    path('login/',login_page,name='login'),
    path('logout/',logout_user,name='logout'),
    path('',QuizListView.as_view(),name='main-view'),
    path('<pk>/',quiz_view,name = 'quiz-view'),
    path('<pk>/data/',quiz_data_view,name = 'quiz_data_view'),
    path('<pk>/save/',save_quiz_view,name = 'save-view'),
    path('<pk>/result/',final_results_page,name='final-result'),
]

quizproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('quizes.urls', namespace='quizes')),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATICFILES_DIRS)

quizes/models.py
from django.db import models
import random

# Create your models here.

DIFF_CHOICES = (
    ('Easy', 'Easy'),
    ('Medium', 'Medium'),
    ('Hard', 'Hard'),
)

class Quiz(models.Model):
    name = models.CharField(max_length=120)
    topic = models.CharField(max_length=120)
    number_of_questions = models.IntegerField()
    time = models.IntegerField(help_text="duration of the quiz in minutes")
    required_score_to_pass = models.IntegerField(help_text="required score in %")
    difficulty = models.CharField(max_length=6, choices=DIFF_CHOICES)

    def __str__(self):
        return f"{self.name}-{self.topic}"

    def get_questions(self):
        questions = list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]

    class Meta:
        verbose_name_plural = 'Quizes'

quizes/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

quizes/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views import generic
from .models import Quiz
from django.views.generic import ListView
from django.http import JsonResponse
from questions.models import Question, Answer
from results.models import Result,TempResultToStoreBetweenRequests
from django.contrib.auth import authenticate, login, logout
from .forms import CreateUserForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


def register_page(request): #register page rendering
    user = request.user
    if user.is_authenticated:
        return redirect('quizes:main-view')
    form = CreateUserForm                 #for creating custom form
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():                         
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account created successfully for '+user)
            return redirect('quizes:login')
    context = {'form':form}
    return render(request, 'quizes/register.html',context)

def login_page(request):    #login page rendering
    user = request.user
    if user.is_authenticated:
        return redirect('quizes:main-view')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request,username = username, password = password)
        if user is not None:
            login(request, user)
            return redirect('quizes:main-view')
        else:
            messages.info(request, 'Username or Password is incorrect')
            
    context = {}
    return render(request, 'quizes/login.html',context)

def logout_user(request):  #logout page rendering
    logout(request)
    return redirect('quizes:login')


class QuizListView(LoginRequiredMixin,ListView):   #To list all the quiz available in homepage
    login_url = '/login/'
    model = Quiz
    template_name = 'quizes/main.html'
    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super(QuizListView,self).get_context_data(**kwargs) 
        context['user']= user
        return context  


@login_required(login_url='/login')
def quiz_view(request,pk):                      
    user = request.user 
    session_id = request.session.session_key                        
    TempResultToStoreBetweenRequests.objects.filter(user=user, session_id = session_id).delete()
    quiz = Quiz.objects.get(pk = pk)
    return render(request, 'quizes/quiz.html',{'obj':quiz})

@login_required(login_url='/login')
def quiz_data_view(request, pk):
# the quiz.js handles the get request for this view, takes all the the question which is already randomised to the front end. no matter how many questions are in a quiz, only the specified no of questions are shown to the user
    quiz = Quiz.objects.get(pk = pk)
    question = []
    for q in quiz.get_questions():
        answers = []
        for a in q.get_answers():
            answers.append(a.text)
        question.append({str(q):answers})

    return JsonResponse({'data':question,
        'time':quiz.time})


@login_required(login_url='/login')
def save_quiz_view(request, pk):
#this view involves checking the response given by the user.
    user = request.user
    session_id = request.session.session_key

    score = 0
    questions = []
    if request.is_ajax():
        data = request.POST   #we need to transform querydict to normal data, That is why data_ is declared
        data_ = dict(data.lists())
        data_.pop('csrfmiddlewaretoken')
        for k in data_.keys():
            question = Question.objects.get(text = k)
            questions.append(question)
        
        results = []
        correct_answer = None

        for q in questions:
            a_selected = request.POST.get(q.text)
            
            question_answers = Answer.objects.filter(question=q)
            for a in question_answers:
                if a_selected == a.text:
                    if a.correct:
                        score = 1
                        correct_answer = a.text
                        break
                else:
                    if a.correct:           
                        correct_answer = a.text
            results.append({str(q):{'correct_answer':correct_answer,'answered':a_selected}})
            TempResultToStoreBetweenRequests.objects.create(question_tracker = str(q),user=user,session_id =session_id,correct_answer_tracker= correct_answer,answered_tracker = a_selected, score_tracker = score)
            
        
            
    return JsonResponse({'results':results})


@login_required(login_url='/login')
def final_results_page(request,pk):
# this view handles the final results and create a record on resuts table
    correct_answers_and_answered = []
    score = 0
    user = request.user
    session_id = request.session.session_key
    string_answer = ''
    message =''
    score_and_answers = TempResultToStoreBetweenRequests.objects.filter(user=user, session_id = session_id)
    for obj in score_and_answers:
        dict_of_reponses = {obj.question_tracker:{'correct_answer':obj.correct_answer_tracker,'answered':obj.answered_tracker}}
        score += obj.score_tracker
        correct_answers_and_answered.append(dict_of_reponses)
        
    quiz = Quiz.objects.get(pk = pk)
    multiplier = 100/quiz.number_of_questions
    percent_score = score*multiplier
    if percent_score >= quiz.required_score_to_pass:
        message = 'Congratulations, you passed'
    else:
        message = 'Sorry, try again'


    if request.is_ajax():
        if request.method == 'POST':
            timer_data = request.POST
     
        timer_data_ = dict(timer_data.lists())
        timer_data_str = str(timer_data_['minutes'][0])+':'+str(timer_data_['seconds'][0])

        for question in correct_answers_and_answered:
            for question_name in question.keys():
                string_answer += question[question_name]['answered']
                string_answer += '@#$%'
        
        final_data = {'pk':pk,'quizname':quiz.name,'timerData':timer_data_str,'score':score,'answerSel':correct_answers_and_answered,'percent':round(percent_score,2),'message':message}

        result_update(quiz,user,round(percent_score,2),string_answer,session_id)

    return JsonResponse(final_data)

def result_update(quiz,user,percent_score,string_answer, session_id):
# To create a record on the result table and flush the data on TempResultToStoreBetweenRequests
    Result.objects.create(quiz=quiz,user=user,score=percent_score,answers_selected = string_answer)
    TempResultToStoreBetweenRequests.objects.filter(user=user, session_id = session_id).delete()
    return

quizes/templates/quizes/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
                {% for message in messages %}
                <p id="messages">{{message}}</p>
                {%endfor%}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'quizes:register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

quizes/templates/quizes/main.html
{% extends "base.html" %} {% load static %} {% block scripts %}
<script src="{% static 'quizes/main.js' %}" defer></script>
{% endblock scripts %} {% block title %} Home {% endblock title %}
{% block content%}
<style>
  #logout {
    position: absolute;
    top: 20px;
    right: 16px;
    font-size: 18px;
  }

</style>
<!-- Modal -->
<div
  class="modal fade"
  id="quizStartModal"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Start ?</h5>
        <button
          type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="modal-body-confirm"></div>
      <div class="modal-footer">
        <button type="button" id="start-button" class="btn btn-success">
          Yes
        </button>
        <button type="button" class="btn btn-danger" data-dismiss="modal">
          No
        </button>
      </div>
    </div>
  </div>
</div>



<div id="logout"></div>

<div class="h1">Hi, {{user.username}} here is the Quiz list</div>
<hr />
{% for obj in object_list %}
<button
  class="btn btn-link modal-button"
  data-pk="{{obj.pk}}"
  data-quiz="{{obj.name}}"
  data-topic = "{{obj.topic}}"
  data-question="{{obj.number_of_questions}}"
  data-difficulty="{{obj.difficulty}}"
  data-time="{{obj.time}}"
  data-pass="{{obj.required_score_to_pass}}"
  data-toggle="modal"
  data-target="#quizStartModal"
>
  {{obj.name}}
</button>
<br />
{% endfor %} {% endblock content %}

quizes/templates/quizes/quiz.html
{% extends "base.html" %}
{%load static %}
{%block scripts %}
    <script src="{% static 'quizes/quiz.js' %}" defer></script>
{% endblock scripts %}
{% block title %}
    {{obj.name}}
    
{%endblock title%}
{%block content%}
    <b id = "titlequiz">{{obj.name}}</b>
    <p id = "reqscoretopass">Score to pass: {{obj.required_score_to_pass}}%</p>
    <form id="quiz-form" class="mt-3 mb-3">
        {%csrf_token %}
        <div id= "quiz-box"></div>
    </form>
    <button type= "submit" id="submit-btn" class="btn btn-primary mt-3">submit</button>
    <button type="button" id="next-btn" class="btn btn-primary mt-3">
        Next
      </button>
      <hr>
    <div id = "time-box">
        <b><label id="minutes">00</label>:<label id="seconds">00</label></b>
    </div>
    <div id = "result-box"></div>
{% endblock content%}

quizes/templates/quizes/register.html
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <!-- <link rel="shortcut icon" href="#" /> -->
	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>
                {{form.errors}}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account?  <a href= "{% url 'quizes:login' %}"> Login</a> 
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields

		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>